{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE ApplicativeDo #-}
{-# LANGUAGE BinaryLiterals #-}
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE CApiFFI #-}
{-# LANGUAGE CPP #-}
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE DatatypeContexts #-}
{-# LANGUAGE DeepSubsumption #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DoAndIfThenElse #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE EmptyDataDeriving #-}
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE ExplicitLevelImports #-}
{-# LANGUAGE ExtendedDefaultRules #-}
{-# LANGUAGE ExtendedLiterals #-}
{-# LANGUAGE FieldSelectors #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE GHCForeignImportPrim #-}
{-# LANGUAGE HexFloatLiterals #-}
{-# LANGUAGE ImplicitStagePersistence #-}
{-# LANGUAGE ImpredicativeTypes #-}
{-# LANGUAGE IncoherentInstances #-}
{-# LANGUAGE InterruptibleFFI #-}
{-# LANGUAGE LexicalNegation #-}
{-# LANGUAGE LiberalTypeSynonyms #-}
{-# LANGUAGE LinearTypes #-}
{-# LANGUAGE ListTuplePuns #-}
{-# LANGUAGE MonadComprehensions #-}
{-# LANGUAGE MonomorphismRestriction #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE MultilineStrings #-}
{-# LANGUAGE NPlusKPatterns #-}
{-# LANGUAGE NamedDefaults #-}
{-# LANGUAGE NamedWildCards #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE NondecreasingIndentation #-}
{-# LANGUAGE NullaryTypeClasses #-}
{-# LANGUAGE OrPatterns #-}
{-# LANGUAGE OverlappingInstances #-}
{-# LANGUAGE OverloadedRecordUpdate #-}
{-# LANGUAGE PartialTypeSignatures #-}
{-# LANGUAGE PostfixOperators #-}
{-# LANGUAGE QualifiedDo #-}
{-# LANGUAGE QuantifiedConstraints #-}
{-# LANGUAGE RebindableSyntax #-}
{-# LANGUAGE RequiredTypeArguments #-}
{-# LANGUAGE RoleAnnotations #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StarIsType #-}
{-# LANGUAGE StaticPointers #-}
{-# LANGUAGE Strict #-}
{-# LANGUAGE TraditionalRecordSyntax #-}
{-# LANGUAGE TypeAbstractions #-}
{-# LANGUAGE TypeFamilyDependencies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UnboxedSums #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE UndecidableSuperClasses #-}
{-# LANGUAGE UnicodeSyntax #-}
{-# LANGUAGE UnliftedDatatypes #-}
{-# LANGUAGE UnliftedFFITypes #-}
{-# LANGUAGE UnliftedNewtypes #-}
{-# LANGUAGE NoArrows #-}
{-# LANGUAGE NoBangPatterns #-}
{-# LANGUAGE NoConstrainedClassMethods #-}
{-# LANGUAGE NoDataKinds #-}
{-# LANGUAGE NoDefaultSignatures #-}
{-# LANGUAGE NoDeriveAnyClass #-}
{-# LANGUAGE NoDeriveDataTypeable #-}
{-# LANGUAGE NoDeriveFoldable #-}
{-# LANGUAGE NoDeriveFunctor #-}
{-# LANGUAGE NoDeriveGeneric #-}
{-# LANGUAGE NoDeriveLift #-}
{-# LANGUAGE NoDeriveTraversable #-}
{-# LANGUAGE NoDerivingStrategies #-}
{-# LANGUAGE NoDisambiguateRecordFields #-}
{-# LANGUAGE NoEmptyCase #-}
{-# LANGUAGE NoEmptyDataDecls #-}
{-# LANGUAGE NoExplicitForAll #-}
{-# LANGUAGE NoExplicitNamespaces #-}
{-# LANGUAGE NoForeignFunctionInterface #-}
{-# LANGUAGE NoFunctionalDependencies #-}
{-# LANGUAGE NoGADTSyntax #-}
{-# LANGUAGE NoGeneralizedNewtypeDeriving #-}
{-# LANGUAGE NoImplicitParams #-}
{-# LANGUAGE NoImportQualifiedPost #-}
{-# LANGUAGE NoInstanceSigs #-}
{-# LANGUAGE NoKindSignatures #-}
{-# LANGUAGE NoLambdaCase #-}
{-# LANGUAGE NoMagicHash #-}
{-# LANGUAGE NoMonoLocalBinds #-}
{-# LANGUAGE NoMultiWayIf #-}
{-# LANGUAGE NoNumDecimals #-}
{-# LANGUAGE NoNumericUnderscores #-}
{-# LANGUAGE NoOverloadedLabels #-}
{-# LANGUAGE NoOverloadedLists #-}
{-# LANGUAGE NoOverloadedRecordDot #-}
{-# LANGUAGE NoOverloadedStrings #-}
{-# LANGUAGE NoPackageImports #-}
{-# LANGUAGE NoParallelListComp #-}
{-# LANGUAGE NoPatternGuards #-}
{-# LANGUAGE NoPatternSynonyms #-}
{-# LANGUAGE NoPolyKinds #-}
{-# LANGUAGE NoQuasiQuotes #-}
{-# LANGUAGE NoRankNTypes #-}
{-# LANGUAGE NoRecordPuns #-}
{-# LANGUAGE NoRecordWildCards #-}
{-# LANGUAGE NoRecursiveDo #-}
{-# LANGUAGE NoStandaloneDeriving #-}
{-# LANGUAGE NoStandaloneKindSignatures #-}
{-# LANGUAGE NoStrictData #-}
{-# LANGUAGE NoTemplateHaskell #-}
{-# LANGUAGE NoTemplateHaskellQuotes #-}
{-# LANGUAGE NoTransformListComp #-}
{-# LANGUAGE NoTupleSections #-}
{-# LANGUAGE NoTypeApplications #-}
{-# LANGUAGE NoTypeData #-}
{-# LANGUAGE NoTypeFamilies #-}
{-# LANGUAGE NoTypeOperators #-}
{-# LANGUAGE NoTypeSynonymInstances #-}
{-# LANGUAGE NoUnboxedTuples #-}
{-# LANGUAGE NoViewPatterns #-}
{-# LANGUAGE CUSKs #-}
{-# LANGUAGE ImplicitPrelude #-}
{-# OPTIONS_GHC -Wmissing-deriving-strategies #-}
{-# OPTIONS_GHC -Wmissing-kind-signatures #-}
{-# OPTIONS_GHC -Wmissing-poly-kind-signatures #-}
{-# OPTIONS_GHC -Wmissing-role-annotations #-}
{-# OPTIONS_GHC -Wprepositive-qualified-module #-}
{-# OPTIONS_GHC -Wstar-is-type #-}
{-# OPTIONS_GHC -Wpattern-namespace-specifier #-}
{-# OPTIONS_GHC -fplugin-opt GhcCompat:minVersion=9.14.1 #-}
{-# OPTIONS_GHC -fwarn-deriving-typeable #-}

module Test.Min_9_14_1 (force) where

force :: ()
force = ()
