{-# LANGUAGE CPP #-}
{-# LANGUAGE DatatypeContexts #-}
{-# LANGUAGE DisambiguateRecordFields #-}
{-# LANGUAGE DoAndIfThenElse #-}
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE ExtendedDefaultRules #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE GHCForeignImportPrim #-}
{-# LANGUAGE IncoherentInstances #-}
{-# LANGUAGE LiberalTypeSynonyms #-}
{-# LANGUAGE MonomorphismRestriction #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE NPlusKPatterns #-}
{-# LANGUAGE OverlappingInstances #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RebindableSyntax #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE UnicodeSyntax #-}
{-# LANGUAGE UnliftedFFITypes #-}
{-# LANGUAGE NoArrows #-}
{-# LANGUAGE NoBangPatterns #-}
{-# LANGUAGE NoConstrainedClassMethods #-}
{-# LANGUAGE NoDeriveDataTypeable #-}
{-# LANGUAGE NoEmptyDataDecls #-}
{-# LANGUAGE NoExplicitForAll #-}
{-# LANGUAGE NoForeignFunctionInterface #-}
{-# LANGUAGE NoFunctionalDependencies #-}
{-# LANGUAGE NoGeneralizedNewtypeDeriving #-}
{-# LANGUAGE NoImplicitParams #-}
{-# LANGUAGE NoKindSignatures #-}
{-# LANGUAGE NoMagicHash #-}
{-# LANGUAGE NoMonoLocalBinds #-}
{-# LANGUAGE NoOverloadedStrings #-}
{-# LANGUAGE NoPackageImports #-}
{-# LANGUAGE NoParallelListComp #-}
{-# LANGUAGE NoPatternGuards #-}
{-# LANGUAGE NoQuasiQuotes #-}
{-# LANGUAGE NoRecordPuns #-}
{-# LANGUAGE NoRecordWildCards #-}
{-# LANGUAGE NoRecursiveDo #-}
{-# LANGUAGE NoStandaloneDeriving #-}
{-# LANGUAGE NoTemplateHaskell #-}
{-# LANGUAGE NoTransformListComp #-}
{-# LANGUAGE NoTupleSections #-}
{-# LANGUAGE NoTypeOperators #-}
{-# LANGUAGE NoTypeSynonymInstances #-}
{-# LANGUAGE NoUnboxedTuples #-}
{-# LANGUAGE NoViewPatterns #-}
{-# LANGUAGE ImplicitPrelude #-}
{-# OPTIONS_GHC -fplugin-opt GhcCompat:minVersion=7.0.1 #-}

module Test.Min_7_0_1 (force) where

force :: ()
force = ()
